name: Build
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-?[a-zA-z]*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: KeisukeYamashita
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: keisukeyamashita/spinnaker-github-proxy/spinnaker-github-proxy
          tag_with_ref: true
